name: Docker

on:
  schedule:
    - cron: '00 00 * * 2'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build docker image
        run: |
          docker build -t talosi/mvn-spring-native:graalvm-ce-java17-linux-amd64-22.3.0 -t talosi/mvn-spring-native .
      - name: Check if the image is present on the system
        run: |
          docker images
      - name: Try login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the new docker images with version tag
        run: |
          docker push talosi/mvn-spring-native:1.0
      - name: Push the new docker images with latest tag
        run: |
          docker push talosi/mvn-spring-native:latest